// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '###########################################',
    appId: '1:1045480501442:web:a7e1afb0ab5e7ab53fcb5b',
    messagingSenderId: '1045480501442',
    projectId: 'assignment-2-yousef',
    authDomain: 'assignment-2-yousef.firebaseapp.com',
    storageBucket: 'assignment-2-yousef.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '###########################################',
    appId: '1:1045480501442:android:b46a44bf0a2c98773fcb5b',
    messagingSenderId: '1045480501442',
    projectId: 'assignment-2-yousef',
    storageBucket: 'assignment-2-yousef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '###########################################',
    appId: '1:1045480501442:ios:82c3271c65c30c643fcb5b',
    messagingSenderId: '1045480501442',
    projectId: 'assignment-2-yousef',
    storageBucket: 'assignment-2-yousef.firebasestorage.app',
    iosBundleId: 'com.example.assignment2y',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAblgdd7oXi95rUuYjrci7S3lBbJvzKVA',
    appId: '1:1045480501442:ios:82c3271c65c30c643fcb5b',
    messagingSenderId: '1045480501442',
    projectId: 'assignment-2-yousef',
    storageBucket: 'assignment-2-yousef.firebasestorage.app',
    iosBundleId: 'com.example.assignment2y',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC43f17bzamZ_jLahPIwzdbuuQHEFxsHns',
    appId: '1:1045480501442:web:edb00e894bd23bf23fcb5b',
    messagingSenderId: '1045480501442',
    projectId: 'assignment-2-yousef',
    authDomain: 'assignment-2-yousef.firebaseapp.com',
    storageBucket: 'assignment-2-yousef.firebasestorage.app',
  );
}
